services:

  slimtorq-control:
    image: phillipmaree/slimtorq-control:latest
    build:
      context: .
      dockerfile: ./compose/control/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - artifacts:/data/artifacts
    networks:
      - network_bridge

volumes:
  artifacts:

networks:
  network_bridge:
    driver: bridge
